### PR TITLE
Add support for Go1.16

### PR DESCRIPTION
**Pull request by renzhexigua**
As Go v1.16 (released 2021/02/16) introduced a new MagicNumber [`0xFFFFFFFA`](https://github.com/golang/go/blob/a54f7fc0fde79e8edc696de002fe8a73604f077f/src/runtime/symtab.go#L360) and [`pcHeader`](https://github.com/golang/go/blob/a54f7fc0fde79e8edc696de002fe8a73604f077f/src/runtime/symtab.go#L378) field within the `moduledata` struct(fields order was also changed), the origin go_parser cannot parse the new binary format very well.

I changed a bit (based on the py3 branch) to comply with the new format spec and other fields to analyze some Go-Malware samples compiled by Go v1.16+.  #11 mentioned that IDA introduced some golang-related features, but I doubt that whether it can keep up with the dev speed of Go. 😂

I recommend @0xjiayu accept this PR to a new branch, like py3_1.16, other than merge to the py3 branch directly. The moduledata even the calling convention may change tomorrow. ([Golang issues#40724: switch to a register-based calling convention for Go functions](https://github.com/golang/go/issues/40724)) 😂 To achieve that, I/you will edit this PR's base after you create a new branch first.

As you said in [安全客: 定位 pclntab](https://www.anquanke.com/post/id/215419#h4-7-2-1-pclntab):

> the majority of the go parser tools relied upon this magic number.

The find-by-magicnumber strategy is a little tricky, and it could be used as an anti-analysis method. 

- Recompile Go from source to define my own MagicNumber to disrupt analysts and tools.
- Change `moduledataverify1` function or redefine the moduledata struct layout.
- ...

 A long long way to go for us analysts. Solve the problem first, then optimize.

### CODE REVIEW

**Comment by wonderkun** [comment]
Good job! But I holp this tools can  recognize the go version by itself other than chose different  go_parse branch by us. So after I test your code, I will merge your modify to branch python3.

**Comment by mnill** [comment]
This really help me, thanks

**Comment by 0xjiayu** [comment]
Now go_parser has been upgraded to support Go1.16 and Go1.18. Please use the latest codes.

**Comment by renzhexigua** [comment]
Thanks to @0xjiayu for the newest feature updates. By the way, I'll share with you another tool [GoReSym](https://github.com/mandiant/GoReSym) by the Mandiant team that supports parsing upstream's Golang inner structure natively. In this year's event, I encountered some modified samples and this tool gave me a lot of help.

**Comment by 0xjiayu** [comment]
GoReSym is also an awesome tool, thanks for you recommendation :-)

**Pull request closed without merging**
